// Room Types
const ROOM_TYPES = ['SINGLE', 'DOUBLE', 'TRIPLE', 'QUAD', 'DORMITORY'];

// Assignment Statuses
const ASSIGNMENT_STATUSES = ['ACTIVE', 'INACTIVE', 'PENDING'];

// Maintenance Issue Types
const MAINTENANCE_ISSUE_TYPES = ['ELECTRICAL', 'PLUMBING', 'STRUCTURAL', 'CLEANING', 'SECURITY', 'OTHER'];

// Maintenance Priority Levels
const MAINTENANCE_PRIORITY = ['LOW', 'MEDIUM', 'HIGH', 'URGENT'];

// Maintenance Status
const MAINTENANCE_STATUS = ['PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'];

// Report Types
const REPORT_TYPES = ['OCCUPANCY', 'MAINTENANCE', 'FINANCIAL', 'INCIDENT', 'GENERAL'];

module.exports = {
  ROOM_TYPES,
  ASSIGNMENT_STATUSES,
  MAINTENANCE_ISSUE_TYPES,
  MAINTENANCE_PRIORITY,
  MAINTENANCE_STATUS,
  REPORT_TYPES
};
